name: Create Release

on:
  push:
    branches: [main, staging]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  release:
    uses: ilovepatatos-rust/github-workflows/.github/workflows/release.yml@main
    with:
      project: src/TriggersExt/TriggersExt.csproj
      asset: Oxide.Ext.TriggersExt.dll
      targets: oxide
      publicize: false
      keep_versions: -1
    secrets: inherit
